export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_APPOINTMENT_TIME = 'CART_SAVE_APPOINTMENT_TIME'
export const CART_EMPTY = 'CART_EMPTY'